import type { VerticesMatrix } from "@chthonic/string-art"

interface SvgParams {
  verticesMatrix: VerticesMatrix
  size?: number
  strokeWidth?: number
  strokeColour?: string
}

/**
 * Converts vertexMatrix into an SVG polygon string.
 * @param SvgParams - Options object
 * @param SvgParams.verticesMatrix - A VerticesMatrix generated by a string-art class
 * @param SvgParams.size - The size in px of the generated svg
 * @param SvgParams.strokeWidth - The stroke-width value on the svg
 * @param SvgParams.strokeColour - The stroke-color value on the svg
 *
 * @returns {string} Xml string for a http://www.w3.org/2000/svg svg polygon
 */
export function generateSVGFromVerticesMatrix({
  verticesMatrix,
  size,
  strokeWidth,
  strokeColour,
}: SvgParams): string {
  const hasSize = size !== undefined
  const hasStrokeWidth = strokeWidth !== undefined
  const hasStrokeColour = strokeColour !== undefined
  const scale = hasSize ? size * 2 : 150

  const svgHead = [
    `<svg`,
    hasSize ? `width="${size}" height="${size}"` : false,
    `viewBox="${scale * -1} ${scale * -1} ${scale * 2} ${scale * 2}"`,
    `xmlns="http://www.w3.org/2000/svg">`,
  ]
    .filter((item) => item !== false)
    .join(" ")

  const minimizeCoordinate = (point: number) => {
    const snapToZeroThreshold = 1e-9
    if (Math.abs(point) < snapToZeroThreshold) return 0
    return point.toFixed(2).replace(/\.00$/, "")
  }

  const scaledPoints = verticesMatrix
    .map(
      (point) =>
        `${minimizeCoordinate(point.x * scale)},${minimizeCoordinate(-point.y * scale)}`,
    )
    .join(" ")

  const polygon = [
    `<polygon`,
    `points="${scaledPoints}"`,
    `fill="none"`,
    hasStrokeColour ? `stroke="${strokeColour}"` : false,
    hasStrokeWidth ? `stroke-width="${strokeWidth}"` : false,
    `/>`,
  ]
    .filter((item) => item !== false)
    .join(" ")

  return `${svgHead}\n  ${polygon}\n</svg>`
}
