import type { VerticesMatrix } from "@chthonic/string-art"

interface SvgParams {
  verticesMatrix: VerticesMatrix
  size: number
  strokeWidth: number
  strokeColour: string
}

/**
 * Converts vertexMatrix into an SVG polygon string.
 * @param SvgParams - Options object
 * @param SvgParams.verticesMatrix - A VerticesMatrix generated by a string-art class
 * @param SvgParams.size - The size in px of the generated svg
 * @param SvgParams.strokeWidth - The stroke-width value on the svg
 * @param SvgParams.strokeColour - The stroke-color value on the svg
 *
 * @returns {string} Xml string for a http://www.w3.org/2000/svg svg polygon
 */
export function generateSVGFromVerticesMatrix({
  verticesMatrix,
  size,
  strokeWidth,
  strokeColour,
}: SvgParams): string {
  const scale = size * 2
  const svgHeader = `<svg width="${size}" height="${size}" viewBox="${
    scale * -1
  } ${scale * -1} ${scale * 2} ${
    scale * 2
  }" xmlns="http://www.w3.org/2000/svg">`
  const svgFooter = `</svg>`

  const scaledPoints = verticesMatrix
    .map((p) => `${p.x * scale},${-p.y * scale}`)
    .join(" ")

  const polygon = `<polygon points="${scaledPoints}" fill="none" stroke="${strokeColour}" stroke-width="${strokeWidth}" />`

  return `${svgHeader}\n  ${polygon}\n${svgFooter}`
}
